version: '3'

tasks:
  default:
    aliases:
      - list
    desc: List all tasks
    cmd: task -l

  home-manager:switch:
    desc: |
      Build and activate configuration.
      Usage:
      task run -- <host>
    vars:
      HOST: "{{.CLI_ARGS}}"
    cmds:
      - nix run home-manager -- switch --flake .#{{.HOST}}
