# required Nerd Font
scan_timeout = 0
add_newline = true

format = """
$all \
$time\
$line_break \
$jobs\
$battery\
$status\
$os\
$container\
$shell\
$character"""

[username]
show_always = true
style_user = '#04d500'
format = '[$user]($style) '

[localip]
ssh_only = false
format = '@[$localipv4](bold red) '
disabled = false

[directory]
truncation_length = 100
truncate_to_repo = false
read_only = " 󰌾"

[git_branch]
symbol = " "

[docker_context]
symbol = " "

[golang]
symbol = " "

[nodejs]
symbol = " "

[rust]
symbol = " "

[time]
disabled = false
time_format = '%F(%a) %T'

[os]
disabled = false
style = "bold white"
[os.symbols]
Arch = "[ ](bold #168ECA)"

[character]
error_symbol = "[✗](bold red)"
success_symbol = "[➜](bold green)"
